#!/usr/bin/env bash
# Runs a command to ensure that an app
# has a postgres database when it is starting

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1";
dokku aws-s3:stop "${APP}"
echo "S3 fake container ${APP} removed"
