#!/usr/bin/env bash
source "$PLUGIN_DATA_ROOT/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

s3-run-cmd() {
  APP=$1
  docker run --name "${APP}-s3" -p 5000:80 convox/aws-s3
}

s3-run-cmd "$@"
